tokenizer:
  model_name: /stage/llama-tokenizer
  add_bos_token: False
  decode_with_prefix_space: True
  truncation_side: left
  pad_token_as_eos_token: True

reward_fn:
  id: learned_reward
  args:
    model_name: lvwerra/distilbert-imdb
    label_ix: 1
    include_prompt_for_eval: True

datapool:
  id: imdb
  args: {}

env:
  n_envs: 4
  args:
    max_prompt_length: 64
    max_episode_length: 48
    terminate_on_eos: True

alg:
  id: ppo
  args:
    n_steps: 128
    batch_size: 4
    verbose: 1
    learning_rate: 0.000001
    n_epochs: 5

  kl_div:
    coeff: 0.1
    target_kl: 0.5
  policy:
    id: causal_lm_actor_critic_policy
    args:
      model_name: /stage/llama-7b
      #apply_model_parallel: True
      generation_kwargs:
        do_sample: True
        min_length: 48
        max_new_tokens: 48

train_evaluation:
  eval_batch_size: 8
  n_iters: 10
  eval_every: 2
  save_every: 2
  metrics:
    - id: learned_reward
      args:
        model_name: lvwerra/distilbert-imdb
        label_ix: 1
        batch_size: 100