tokenizer:
  model_name: /net/nfs.cirrascale/mosaic/raja/llama/llama-tokenizer
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: True
  max_length: 64

datapool:
  id: "daily_dialog"
  args:
    context_size: 5

alg:
  id: supervised
  training_args:
    per_device_train_batch_size: 1
    logging_steps: 200
    num_train_epochs: 10
    lr_scheduler_type: "constant"
    learning_rate: 0.00001
    save_total_limit: 1
    fsdp: "full_shard auto_wrap"
    fsdp_config:
      default_auto_wrap_policy: 'transformer_auto_wrap_policy'
      fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
  model_type: causal
  model_name: /net/nfs.cirrascale/mosaic/raja/llama/llama-13b
  generation_kwargs:
    do_sample: True
    top_k: 20
    min_length: 2
    max_new_tokens: 20
    post_processing_fn: null

train_evaluation:
  eval_batch_size: 1
  eval_every: 1
  save_every: 1
  metrics:
    - id: diversity
      args: {}


