tokenizer:
  model_name: EleutherAI/gpt-j-6B
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: True
  max_length: 64

datapool:
  id: "imdb_seq2seq"
  args:
    positive_ratio: 1.0

alg:
  id: supervised
  training_args:
    per_device_train_batch_size: 2
    logging_steps: 200
    num_train_epochs: 10
    lr_scheduler_type: "constant"
    learning_rate: 0.00001
    save_total_limit: 1
    fsdp: "auto_wrap"
    #fsdp_config:
      #fsdp_transformer_layer_cls_to_wrap: GPTJBlock
    #  fsdp_backward_prefetch: "backwards_pre"
  model_type: causal
  model_name: EleutherAI/gpt-j-6B
  generation_kwargs:
    do_sample: True
    top_k: 20
    min_length: 2
    max_new_tokens: 20
    post_processing_fn: null

train_evaluation:
  eval_batch_size: 4
  save_every: 51
  metrics:
    - id: diversity
      args: {}

